import React, { useEffect, useState } from "react"
import { multicastAsyncIterable } from "../../utils/multicastAsyncIterable"
import { streamTextInChunks } from "../../utils/streamTextInChunks"
import { listenTo } from "../../utils/listenTo"
import JsonStreamCodeView from "../../components/JsonStreamCodeView"
import CodeSnippet from "../../components/CodeSnippet"
import { TraditionalCard } from "./TraditionalCard"
import { StreamingCard } from "./StreamingCard"

let hasRunMainDemoEffect = false

const exampleJson = JSON.stringify({
    title: 'Parsing Streaming JSON from LLMs has never been easier!',
    author: 'Vincent Sanicolas',
    description: 'Now, you can listen to properties within your stream as a stream, or await the full value as a promise!',
    features: [
        `Subscribe to individual properties' paths as streams and promises.`,
        `Receive values as they are generated by the LLM in real-time.`,
        `Reactive lists that fire AS SOON AS an item starts generating`,
        `Race conditions handled for you automatically`,
        `Compatible with any Typescript projects`,
    ],
    image: {
        url: 'https://raw.githubusercontent.com/ComsIndeed/json_stream_parser_demo/main/assets/cover.jpg',
        generated_with: 'Gemini'
    }
})

export default function MainDemo() {
    const [previewValue, setJsonStreamValue] = useState<string>("")
    const [traditionalParserIterable, setTraditionalParserIterable] = useState<AsyncIterable<string> | null>(null)
    const [streamingParserIterable, setStreamingParserIterable] = useState<AsyncIterable<string> | null>(null)

    useEffect(() => {
        if (hasRunMainDemoEffect) return
        hasRunMainDemoEffect = true

        // Create streams
        const iterable = streamTextInChunks(exampleJson, 5, 100);
        const [preview, traditionalParser, streamingParser] = multicastAsyncIterable(iterable, 3);

        setTraditionalParserIterable(traditionalParser);
        setStreamingParserIterable(streamingParser);

        // Update the full JSON stream as it comes in
        listenTo(preview, (value) => {
            setJsonStreamValue((prev) => prev + value);
        })

    }, [])

    return (
        <div
            id="MainDemo"
            style={{
                display: 'flex',
                gap: '16px',
                alignItems: 'flex-start',
                padding: '16px',
                boxSizing: 'border-box',
                width: '100%',
                alignContent: 'center',
                justifyContent: 'center',
            }}
        >

            <div
                id="StreamControls"
                style={{ flex: '0 0 40.333%', minWidth: 0, maxWidth: '40.333%', overflow: 'hidden', boxSizing: 'border-box' }}
            >
                <div style={cardStyle}>
                    <h2 style={{ marginTop: 0 }}>LLM JSON Stream</h2>
                    <JsonStreamCodeView jsonStreamFullValue={exampleJson} jsonStreamValue={previewValue} textStyle={{ fontSize: 14 }} />
                </div>

                <div style={cardStyle}>
                    <CodeSnippet code={"const titleIterable = parser.getStringProperty('title');"} style={{ fontSize: 14 }} />
                    <CodeSnippet code={"const authorIterable = parser.getStringProperty('author');"} style={{ fontSize: 14 }} />
                    <CodeSnippet code={"const descriptionIterable = parser.getStringProperty('description');"} style={{ fontSize: 14 }} />
                    <CodeSnippet code={"const imageUrlIterable = parser.getStringProperty('image.url');"} style={{ fontSize: 14 }} />
                </div>

            </div>

            <div
                id="StreamOutputs"
                style={{ ...cardStyle, backgroundColor: '#ffffff08', flex: '0 0 55.555%', minWidth: 0, maxWidth: '55.555%', overflow: 'hidden', boxSizing: 'border-box', display: 'flex', gap: '16px', alignItems: 'flex-start' }}
            >
                <div style={{ flex: '1 1 50%', minWidth: 0, display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>
                    <h3>Traditional Parsing</h3>
                    <div style={{ flex: '1 1 auto', minHeight: 0, overflow: 'hidden', display: 'flex' }}>
                        <TraditionalCard jsonStreamPreview={traditionalParserIterable} />
                    </div>
                </div>
                <div style={{ flex: '1 1 50%', minWidth: 0, display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>
                    <h3>Stream Parsing</h3>
                    <div style={{ flex: '1 1 auto', minHeight: 0, overflow: 'hidden', display: 'flex' }}>
                        <StreamingCard parserStream={streamingParserIterable} />
                    </div>
                </div>
            </div>

        </div>
    )
}

export const cardStyle: React.CSSProperties = {
    borderRadius: '8px',
    padding: '16px',
    backgroundColor: '#ffffff15',
    margin: '8px',
}
